spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/university
        username: postgres
        password: qwerty
        
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL94Dialect
                jdbc:
                    batch_size: 10
                    fetch_size: 50
    
    data:
        web:
            pageable:
                default-page-size: 10    
                one-indexed-parameters: true                        
                    
    thymeleaf:
        prefix: /WEB-INF/views/
        suffix: .html
     
university:
    maxGroupSize: 20
    minLectureDurationInMinutes: 30
    vacationDays:
        BACHELOR: 15
        MASTER: 20
        DOCTOR: 25      